Micer Readme 1.0
Crazy-Marvin/Flashy pull request #167
Opened 2023-12-05 13:26 UTC by inson1

2023-12-05 22:10 UTC, CrazyMarvin commented
Thanks for the PR, @inson1! 😘

2023-12-05 22:13 UTC, CrazyMarvin commented
I have made a few small suggestions based mainly on my taste preferences.

2023-12-05 22:47 UTC, inson1 commented
@CrazyMarvin Where are the suggestions?

2023-12-05 23:19 UTC, CrazyMarvin commented
> @CrazyMarvin Where are the suggestions?

Don't you see them above?

2023-12-05 23:23 UTC, inson1 commented
@CrazyMarvin Where?
![brave_8l48a8OqKy](https://github.com/Crazy-Marvin/Flashy/assets/75314629/1c4b13ce-96d0-4fc7-aee7-7c029c835416)

2023-12-06 20:30 UTC, CrazyMarvin requested changes

2023-12-06 20:30 UTC, CrazyMarvin commented on README.md
> +      <img alt="Get it on F-Droid" src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png" height="100">
Please use this link so that we do not have to load from another website: https://user-images.githubusercontent.com/15004217/36919296-19b8524e-1e5d-11e8-8962-48463b1cec8a.png

2023-12-06 20:30 UTC, CrazyMarvin commented on README.md
> +      <img alt="Get it on Google Play" src="https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png" height="100">
Please use this link so that we do not have to load from another website: https://user-images.githubusercontent.com/15004217/36810046-fa306856-1cc9-11e8-808e-6eb8a81783c7.png

2023-12-06 20:30 UTC, CrazyMarvin commented on README.md
> +<a href="https://github.com/Crazy-Marvin/Flashy/releases/latest">
F-Droid and Google Play are enough. Let's skip this icon so it does not get too much.

2023-12-06 20:30 UTC, CrazyMarvin commented on README.md
> -[![F-Droid](https://img.shields.io/f-droid/v/rocks.poopjournal.flashy.svg)](https://f-droid.org/en/packages/rocks.poopjournal.flashy/)
Let's keep the F-Droid and Google Play badges additionally please. The Google Play badge is static but the F-Droid badge is dynamic and shows the version that is on F-Droid.

2023-12-06 20:32 UTC, CrazyMarvin commented
> @CrazyMarvin Where? ![brave_8l48a8OqKy](https://private-user-images.githubusercontent.com/75314629/288233830-1c4b13ce-96d0-4fc7-aee7-7c029c835416.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4OTUwMDMsIm5iZiI6MTcwMTg5NDcwMywicGF0aCI6Ii83NTMxNDYyOS8yODgyMzM4MzAtMWM0YjEzY2UtOTZkMC00ZmM3LWFlZTctN2MwMjljODM1NDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDIwMzE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MzFkZjVkYmViNjg4NmYxNmZlZjMxZDc2ZTQ2YzBjMjE0MmE4MmIxMGYzOTNkOTJiYzk5MmI3ZTc3MjJmMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2BL6kGvLw3c_kJ7V-IuFHGU_ZBKD2avwirXTy1dUoM4)

Sorry @inson1, I forgot to publish the review. I left it in draft mode so only I could see it yesterday. 🙈

2023-12-21 22:47 UTC, CrazyMarvin commented
Do you have time to update the PR this week?

2023-12-31 21:27 UTC, merged